name: Daily claim
on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  Daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check for JWT Secret
        id: IsJWT
        shell: bash
        run: |
          if [ "${{ secrets.JWT_TOKEN }}" != '' ]; then
            echo 1 >> $GITHUB_OUTPUT;
          else
            echo 0 >> $GITHUB_OUTPUT;
          fi

      - uses: actions/checkout@v4
      - name: Run HoneygainPot
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          IsJWT: ${{ steps.IsJWT.outputs }}
