name: Daily claim
on:
  workflow_dispatch:

jobs:
  Daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run HoneygainPot with IsJWT Secret
        if: ${{ secrets.JWT_TOKEN != '' }}
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          IsJWT: 1

      - uses: actions/checkout@v4
      - name: Run HoneygainPot without IsJWT Secret
        if: ${{ steps.IsJWT.outputs.available != 'true' }}
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          IsJWT: 0
