name: Daily claim
on:
  workflow_dispatch:

jobs:
  Daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check for JWT Secret
        id: JWTCheck
        shell: bash
        run: |
          if [ "${{ secrets.JWT_TOKEN }}" != '' ]; then
            echo "IsJWT=1" >> $GITHUB_OUTPUT;
          else
            echo "IsJWT=0" >> $GITHUB_OUTPUT;
          fi

      - uses: actions/checkout@v4
      - name: Run HoneygainPot
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }}
          PASS: ${{ secrets.PASS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          IsJWT: ${{ steps.JWTCheck.outputs.IsJWT }}
